language: cpp
sudo: false

compiler:
  - gcc
  - clang

env:
  - CMAKE_BUILD_TYPE=Debug
  - CMAKE_BUILD_TYPE=Release

addons:
  apt:
    sources:
    # CMake 3.x
    - george-edison55-precise-backports
    # gcc-4.9
    - ubuntu-toolchain-r-test
    # clang 3.4
    - llvm-toolchain-precise
    packages:
    - cmake
    - cmake-data
    - ninja-build
    - g++-4.9
    - clang-3.4

install:
  # Use GCC 4.9
  - if [ "$CC" = "gcc" ]; then
      export CC=gcc-4.9 &&
      export CXX="g++-4.9";
    fi

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DRC_ENABLE_TESTS=ON -DRC_ENABLE_EXAMPLES=ON -DRC_ENABLE_GTEST=ON -DRC_ENABLE_GMOCK=ON -DRC_ENABLE_BOOST=ON -DRC_ENABLE_BOOST_TEST=ON -G Ninja ..
  - ninja -j1 # Don't run out of memory, please
  - ctest --output-on-failure